In [10]:
import numpy as np
import pandas as pd

# The Basics

In [11]:
data = [[1,2,3,4],[5,6,7,8]]

In [12]:
arr1 = np.array(data)

In [13]:
arr1.shape

(2, 4)

In [14]:
arr1.ndim

2

In [15]:
arr1.dtype

dtype('int64')

# Broadcasting & Vectorization

In [27]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [28]:
arr1 * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

# Indexing & Slicing

In [22]:
arr1[0]

array([1, 2, 3, 4])

In [23]:
arr1[0][0]

1

In [26]:
arr1[0,0]

1

In [30]:
arr1[:1]

array([[1, 2, 3, 4]])

In [33]:
arr1[1:2]

array([[5, 6, 7, 8]])

In [35]:
arr1[1,:2]

array([5, 6])

# Reshaping & Transposing

In [38]:
arr1.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
arr1.reshape((4,3))

ValueError: cannot reshape array of size 8 into shape (4,3)